# Generated by Django 6.0.2 on 2026-02-24 11:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proprietor', models.TextField()),
                ('plant_species', models.TextField()),
                ('picture', models.TextField()),
                ('review_date', models.DateField()),
                ('reviewer', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('region', models.TextField()),
                ('editor', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nbr_of_boxes', models.IntegerField()),
                ('bee_species', models.TextField()),
                ('bee_amount', models.TextField()),
                ('beekeeper', models.TextField()),
                ('picture', models.TextField()),
                ('disease', models.IntegerField()),
                ('kind_of_disease', models.TextField(null=True)),
                ('average_harvest', models.IntegerField(null=True)),
                ('source', models.TextField(null=True)),
                ('quality', models.TextField(null=True)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
                ('horizontal_accuracy', models.FloatField(null=True)),
                ('nr_used_satellites', models.IntegerField(null=True)),
                ('fix_status_descr', models.TextField(null=True)),
                ('position_locked', models.BooleanField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oapif_demo.area')),
            ],
        ),
        migrations.CreateModel(
            name='PollenConsumption',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oapif_demo.apiary')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oapif_demo.area')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer', models.TextField()),
                ('review_date', models.DateField()),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oapif_demo.apiary')),
            ],
        ),
    ]
