# Generated by Django 5.2 on 2026-02-27 12:59

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("proprietor", models.CharField()),
                ("plant_species", models.CharField()),
                ("picture", models.CharField()),
                ("review_date", models.DateField()),
                ("reviewer", models.CharField()),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField()),
                ("region", models.CharField()),
                ("editor", models.CharField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apiary",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nbr_of_boxes", models.IntegerField(verbose_name="Number of Boxes")),
                ("bee_species", models.CharField(verbose_name="Species of Bees")),
                ("bee_amount", models.CharField(verbose_name="Amount of Bees")),
                ("beekeeper", models.CharField(verbose_name="Beekeeper")),
                ("picture", models.CharField(verbose_name="Photo")),
                ("disease", models.BooleanField(verbose_name="Infected")),
                ("kind_of_disease", models.CharField(blank=True, null=True)),
                (
                    "average_harvest",
                    models.IntegerField(null=True, verbose_name="Yearly Harvest (kg)"),
                ),
                ("source", models.CharField(blank=True, null=True)),
                ("quality", models.CharField(blank=True, null=True)),
                ("x", models.FloatField(blank=True, null=True)),
                ("y", models.FloatField(blank=True, null=True)),
                ("z", models.FloatField(blank=True, null=True)),
                ("horizontal_accuracy", models.FloatField(blank=True, null=True)),
                ("nr_used_satellites", models.IntegerField(blank=True, null=True)),
                ("fix_status_descr", models.CharField(blank=True, null=True)),
                ("position_locked", models.BooleanField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="oapif_demo.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollenConsumption",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "percentage",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "apiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oapif_demo.apiary",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pollen_consumption",
                        to="oapif_demo.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer", models.CharField()),
                ("review_date", models.DateField()),
                (
                    "apiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="oapif_demo.apiary",
                    ),
                ),
            ],
        ),
    ]
